### ISSUE TITLE
Pentacrest widget doesn't support SSL

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/signage.uiowa.edu#11]
https://webcam.iowa.uiowa.edu/live/readImage.asp

**Comment by adamdelaney** [comment]
Rick has emailed Cody to see if we can get a cert for this.

**Comment by richardbporter** [comment]
This won't happen until next summer. The current software is blocking them from implementing a cert now. I guess we need to disable this pane or find some workaround.

**Comment by adamdelaney** [comment]
I ran a new report and it looks like 9 signs are using this.

**Comment by adamdelaney** [comment]
Bill setup a proxy on data.its: https://data.its.uiowa.edu/live/readImage.asp

**Comment by adamdelaney** [comment]
Here are the node ids: 89, 380, 258, 73, 2017, 2285, 9392, 9230, 1115
