### ISSUE TITLE
Ajax errors for widgets

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/signage.uiowa.edu#17]
- EMS
- ITC Availability
- ITC Availability Grid

![unknown](https://user-images.githubusercontent.com/1016880/32346555-b5c13cea-bfdb-11e7-889d-5eff833fb9db.png)

**Comment by richardbporter** [comment]
PHP Fatal error: Call to undefined function signage_signs_itcavailability_build_itc_options() uiowa_signage_panes/plugins/content_types/itcavailability.inc on line 39

**Comment by richardbporter** [comment]
PHP Fatal error:  Call to undefined function dpm() in uiowa_signage_panes/plugins/content_types/ems_events.inc on line 179

**Comment by adamdelaney** [comment]
Removed dpm and added missing function.
